project:
  type: website
  resources:
    - "*.mp3"

website:
  title: "Zhe Cui (崔哲)"
  favicon: favicon.ico
  navbar:
    right:
      - text: 'CV'
        href: cv.qmd
    tools:
      - icon: github
        href: https://www.github.com/chezui
        link-external-newwindow: true
      - icon: mortarboard
        href: https://scholar.google.com/citations?user=qVWbd6wAAAAJ
        link-external-newwindow: true
      - icon: twitter-x
        href: https://www.x.com/_zhecui
        link-external-newwindow: true
      - icon: linkedin
        href: https://www.linkedin.com/in/cuizhe
        link-external-newwindow: true
  repo-url: https://github.com/chezui/zhe.home
  draft-mode: unlinked
  twitter-card: true
  open-graph: true
  site-url: https://zhecui.ca


format:
  html:
    toc: true
    code-copy: true
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    include-in-header: schema.html
    link-external-newwindow: true

editor: source 

execute:
  freeze: auto

