project:
  type: website

website:
  title: "zhe.home"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - search
      - fullscreen
      - icon: github
        href: https://www.github.com/chezui
    repo-url

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

