project:
  type: website
  resources:
    - "*.mp3"

website:
  title: "Zhe Cui (崔哲)"
  favicon: favicon.ico
  navbar:
    right:
      - text: 'About'
        href: about.qmd
    tools:
      - icon: github
        href: https://www.github.com/chezui
      - icon: mortarboard
        href: https://scholar.google.com/citations?user=qVWbd6wAAAAJ
      - icon: twitter-x
        href: https://www.x.com/_zhecui
      - icon: linkedin
        href: https://www.linkedin.com/in/cuizhe
  repo-url: https://github.com/chezui/zhe.home
  repo-actions: [source, edit, issue]
  draft-mode: unlinked
  twitter-card: true
  open-graph: true


format:
  html:
    toc: true
    code-copy: true
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    include-in-header: schema.html
editor: source 

